### ISSUE TITLE
[1.18.1 - Paper] Issue when Resetting & Creating Islands

### ISSUE THREAD

**Issue by InfinityAspire** [BG-Software-LLC/SSB-AcidIslands#1]
Command: /ai reset
Stacktrace:

> [19:10:20] [Server thread/INFO]: Sequacious issued server command: /ai reset
[19:10:20] [Craft Scheduler Thread - 15 - BuycraftX/INFO]: [BuycraftX] Fetching all due players...
[19:10:20] [Craft Scheduler Thread - 15 - BuycraftX/INFO]: [BuycraftX] Fetched due players (0 found).
[19:10:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SuperiorSkyblock2 v1.8.3.424
java.lang.IllegalArgumentException: Plugins must use createChunkData(World) rather than implementing ChunkData: org.bukkit.craftbukkit.v1_18_R1.generator.OldCraftChunkData@50b83b18
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
	at com.bgsoftware.superiorskyblock.nms.v1_18_R1.chunks.IslandsChunkGenerator.a(IslandsChunkGenerator.java:58) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSChunksImpl.removeBlocks(NMSChunksImpl.java:145) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSChunksImpl.lambda$deleteChunks$8(NMSChunksImpl.java:235) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSUtils.runActionOnLoadedChunks(NMSUtils.java:82) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSUtils.runActionOnChunks(NMSUtils.java:72) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.nms.v1_18_R1.NMSChunksImpl.deleteChunks(NMSChunksImpl.java:221) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.utils.islands.IslandUtils.deleteChunks(IslandUtils.java:231) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:850) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.resetChunks(SIsland.java:833) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.island.SIsland.disbandIsland(SIsland.java:1156) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.menu.impl.MenuConfirmDisband.onPlayerClick(MenuConfirmDisband.java:129) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.menu.SuperiorMenu.onClick(SuperiorMenu.java:250) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.bgsoftware.superiorskyblock.listeners.MenusListener.onMenuClick(MenusListener.java:66) ~[SuperiorSkyblock2-[1.8.3-b424].jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor551.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-108]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2817) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-108]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Open an issue on SSB's page
