### ISSUE TITLE
AcidIslands module WaterGenerator

### ISSUE THREAD

**Issue by SurvivorsDev** [BG-Software-LLC/SSB-AcidIslands#11]
### Minecraft's Version

 Paper version 1.20.6-128-master@3181470

### Plugin's Version

Latest stable build 1.0.0 20/01/2024 12:38:57

### Describe the bug

![image](https://github.com/BG-Software-LLC/SSB-AcidIslands/assets/36204486/7fcab292-3dec-47d0-ac2b-02c8420b426d)

### To Reproduce

[01:59:04 WARN]: [SuperiorSkyblock2] Task #2 for SuperiorSkyblock2 v2024.1 generated an exception
java.lang.ExceptionInInitializerError: null
        at com.bgsoftware.ssbacidislands.WaterGenerator.lambda$new$0(WaterGenerator.java:25) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1147) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.bgsoftware.common.reflection.ReflectMethod.<clinit>(ReflectMethod.java:10) ~[?:?]
        ... 6 more
[01:59:05 INFO]: [SuperiorSkyblock2] Detected PaperSpigot - Using async chunk-loading support with PaperMC.

**Comment by OmerBenGera** [comment]
Checkout latest dev build, let me know if it is fixed

**Comment by SurvivorsDev** [comment]
> Checkout latest dev build, let me know if it is fixed

Problem solved, thank you. Could you add terrain for the submarine as an idea?

**Comment by OmerBenGera** [comment]
Open a feature request regarding this :)

**Comment by MynamisTG** [comment]
Its working goood wwith me now at Java 11. Thank u <3. But its look like not work with Java 8. 
Video it work good at java 11 for review: https://drive.google.com/file/d/1y0gSmV5TTjKxmO3uhEVsbG3ivTeD4_dc/view?usp=sharing


[12:01:16 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering module SSBAcidIslands-1.0.0-b11.jar:
[12:01:16 WARN]: java.lang.RuntimeException: An error occurred while reading SSBAcidIslands-1.0.0-b11.jar
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:71)
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerExternalModules(ModulesManagerImpl.java:222)
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.loadData(ModulesManagerImpl.java:52)
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:221)
[12:01:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:01:16 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[12:01:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[12:01:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[12:01:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[12:01:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[12:01:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[12:01:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[12:01:16 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[12:01:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[12:01:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:01:16 WARN]: Caused by: java.lang.UnsupportedClassVersionError: com/bgsoftware/ssbacidislands/util/PlayerUtils has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[12:01:16 WARN]:        at java.lang.ClassLoader.defineClass1(Native Method)
[12:01:16 WARN]:        at java.lang.ClassLoader.defineClass(Unknown Source)
[12:01:16 WARN]:        at java.security.SecureClassLoader.defineClass(Unknown Source)
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.core.io.FileClassLoader.findClass(FileClassLoader.java:91)
[12:01:16 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:01:16 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:01:16 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.core.io.JarFiles.getClass(JarFiles.java:30)
[12:01:16 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.registerModule(ModulesManagerImpl.java:68)
[12:01:16 WARN]:        ... 14 more

**Comment by OmerBenGera** [comment]
> PlayerUtils

Will be fixed, thanks
